"""Render a single self-contained Board dashboard (no external JS/CSS)."""
from __future__ import annotations
import os
import html


def _xaf(n):
    return f"XAF {int(n):,}"


def _bar(label, value, total, color):
    pct = (value / total * 100) if total else 0
    return f"""
    <div class="barrow">
      <div class="barlabel">{html.escape(label)}</div>
      <div class="bartrack"><div class="barfill" style="width:{pct:.1f}%;background:{color}"></div></div>
      <div class="barval">{value}</div>
    </div>"""


def render(run_summary, eval_before, eval_after, baseline, out_path):
    dc = run_summary["decision_counts"]
    n = run_summary["n_applications"]
    total_req = sum(c["requested_amount"] for c in run_summary["cases"])

    colors = {"approve": "#2E7D32", "refer": "#F9A825",
              "decline": "#C62828", "refer_compliance": "#6A1B9A"}
    bars = "".join([
        _bar("Approve", dc.get("approve", 0), n, colors["approve"]),
        _bar("Refer to committee", dc.get("refer", 0), n, colors["refer"]),
        _bar("Decline", dc.get("decline", 0), n, colors["decline"]),
        _bar("Refer - compliance", dc.get("refer_compliance", 0), n, colors["refer_compliance"]),
    ])

    rows = ""
    for c in run_summary["cases"]:
        flags = ", ".join(c.get("flags") or []) or "—"
        badge = {
            "approve": "b-app", "refer": "b-ref", "decline": "b-dec",
            "refer_compliance": "b-comp",
        }.get(c.get("decision"), "b-ref")
        rows += f"""<tr>
          <td>{html.escape(c['id'])}</td>
          <td>{html.escape(c['business_name'])}</td>
          <td>{html.escape(c['sector'])}</td>
          <td>{html.escape(c['region'])}</td>
          <td class="num">{_xaf(c['requested_amount'])}</td>
          <td class="num">{c.get('score') if c.get('score') is not None else '—'}</td>
          <td>{html.escape(str(c.get('rating') or '—'))}</td>
          <td>{html.escape(flags)}</td>
          <td><span class="badge {badge}">{html.escape(str(c.get('decision')))}</span></td>
        </tr>"""

    delta = round(eval_after["architecture_score"] - eval_before["architecture_score"], 1)
    speedup = (baseline["wall_seconds"] / run_summary["wall_seconds"]
               if run_summary["wall_seconds"] else 0)

    sug = "".join(f"<li>{html.escape(s)}</li>" for s in eval_before["suggestions"])

    doc = f"""<!doctype html><html><head><meta charset="utf-8">
<title>Afriland SME Credit Co-pilot — Board View</title>
<style>
 body{{font-family:Segoe UI,Arial,sans-serif;margin:0;background:#f4f6f9;color:#1f2933}}
 .top{{background:#1F4E79;color:#fff;padding:20px 32px}}
 .top h1{{margin:0;font-size:21px}} .top p{{margin:4px 0 0;opacity:.85;font-size:13px}}
 .wrap{{padding:24px 32px;max-width:1100px;margin:0 auto}}
 .cards{{display:flex;gap:16px;flex-wrap:wrap;margin-bottom:8px}}
 .card{{background:#fff;border-radius:10px;padding:16px 18px;flex:1;min-width:160px;
        box-shadow:0 1px 3px rgba(0,0,0,.08)}}
 .card .k{{font-size:12px;color:#647488;text-transform:uppercase;letter-spacing:.04em}}
 .card .v{{font-size:24px;font-weight:700;margin-top:4px}}
 .card .s{{font-size:12px;color:#8595a7;margin-top:2px}}
 .panel{{background:#fff;border-radius:10px;padding:18px 20px;margin-top:18px;
         box-shadow:0 1px 3px rgba(0,0,0,.08)}}
 .panel h2{{margin:0 0 12px;font-size:15px;color:#1F4E79}}
 .barrow{{display:flex;align-items:center;margin:7px 0;font-size:13px}}
 .barlabel{{width:160px}} .bartrack{{flex:1;background:#eceff3;border-radius:6px;height:16px;overflow:hidden}}
 .barfill{{height:16px}} .barval{{width:34px;text-align:right;font-weight:600}}
 table{{width:100%;border-collapse:collapse;font-size:12.5px}}
 th,td{{text-align:left;padding:7px 9px;border-bottom:1px solid #eceff3}}
 th{{background:#1F4E79;color:#fff;font-weight:600;position:sticky;top:0}}
 td.num{{text-align:right;font-variant-numeric:tabular-nums}}
 .badge{{padding:2px 8px;border-radius:10px;color:#fff;font-size:11px;font-weight:600;text-transform:capitalize}}
 .b-app{{background:#2E7D32}} .b-ref{{background:#F9A825}} .b-dec{{background:#C62828}} .b-comp{{background:#6A1B9A}}
 .imp{{display:flex;gap:24px;flex-wrap:wrap;align-items:center}}
 .score{{font-size:34px;font-weight:800;color:#1F4E79}}
 ul{{margin:6px 0 0 18px;font-size:13px}} li{{margin:3px 0}}
 .note{{font-size:11.5px;color:#8595a7;margin-top:18px}}
</style></head><body>
<div class="top">
  <h1>Afriland First Bank — SME Credit Origination Co-pilot</h1>
  <p>Board of Directors view · batch of {n} applications · generated by the multi-agent pipeline</p>
</div>
<div class="wrap">
  <div class="cards">
    <div class="card"><div class="k">Applications</div><div class="v">{n}</div>
      <div class="s">total requested {_xaf(total_req)}</div></div>
    <div class="card"><div class="k">Approved exposure</div><div class="v">{_xaf(run_summary['approved_exposure'])}</div>
      <div class="s">{dc.get('approve',0)} files approved (advisory)</div></div>
    <div class="card"><div class="k">Compliance referrals</div><div class="v">{run_summary['compliance_referrals']}</div>
      <div class="s">auto-blocked from approval</div></div>
    <div class="card"><div class="k">Avg credit score</div><div class="v">{run_summary['avg_score']}</div>
      <div class="s">internal 0–100 scale</div></div>
    <div class="card"><div class="k">Batch time</div><div class="v">{run_summary['wall_seconds']}s</div>
      <div class="s">{speedup:.1f}× vs single-agent baseline</div></div>
  </div>

  <div class="panel">
    <h2>Decision mix</h2>
    {bars}
  </div>

  <div class="panel imp">
    <div>
      <div class="k" style="font-size:12px;color:#647488;text-transform:uppercase">Architecture self-score</div>
      <div class="score">{eval_before['architecture_score']} → {eval_after['architecture_score']}
        <span style="font-size:15px;color:#2E7D32">(+{delta})</span></div>
      <div class="s" style="font-size:12px;color:#8595a7">evaluator agent, 1–10, after one optimization pass</div>
    </div>
    <div style="flex:1;min-width:260px">
      <div class="k" style="font-size:12px;color:#647488;text-transform:uppercase">Evaluator's improvement note</div>
      <ul>{sug}</ul>
    </div>
  </div>

  <div class="panel">
    <h2>Per-application decisions <span style="font-weight:400;color:#8595a7;font-size:12px">— every file requires human credit-officer sign-off</span></h2>
    <table>
      <tr><th>ID</th><th>Business</th><th>Sector</th><th>Region</th><th>Requested</th>
          <th>Score</th><th>Rating</th><th>Flags</th><th>Recommendation</th></tr>
      {rows}
    </table>
  </div>

  <div class="note">
    Recommendations are advisory and were produced by an AI multi-agent pipeline
    (orchestrator + 5 specialists) with a compliance hard-gate and full audit logging.
    Figures derive from submitted application data. Not a final credit decision.
  </div>
</div></body></html>"""

    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    with open(out_path, "w", encoding="utf-8") as f:
        f.write(doc)
    return out_path
